server:
    port: 8090
    #用户会话session过期时间，以秒为单位
    session:
        timeout: 1800
    #默认访问路径，默认为:/
    context-path: null
    #最大线程数
    tomcat:
        max-threads: 1000
spring:
    primary:
        datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/db_test_c3p0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: root
            initialPoolSize: 15
            minPoolSize: 15
            #连接池中保留的最大连接数。Default: 15
            maxPoolSize: 30
            #最大空闲时间,60秒内未使用则连接被丢弃。若为0则永不丢弃。Default:0,单位：秒
            maxIdleTime: 60
            #当连接池中的连接耗尽的时候c3p0一次同时获取的连接数。Default: 3
            acquireIncrement: 3
            #JDBC的标准参数，用以控制数据源内加载的PreparedSt atements数量。但由于预缓存的statements属于单个connection而不是整个连接池。
            #所以设置这个参数需要考虑到多方面的因素。如果maxStatements与maxStatementsPerConnection均为0，则缓存被关闭。Default: 0
            maxStatements: 0
            #获取连接失败将会引起所有等待连接池来获取连接的线程抛出异常。但是数据源仍有效保留，并在下次调用getConnection()的时候继续尝试获取连接。
            #如果设为true，那么在尝试获取连接失败后该数据源将申明已断开并永久关闭。Default: false
            #true表示pool向数据库请求连接失败后标记整个pool为block并close，就算后端数据库恢复正常也不进行重连，客户端对pool的请求都拒绝掉。false表示不会标记 pool为block，
            #新的请求都会尝试去数据库请求connection。默认为false。
            # 因此，如果想让数据库和网络故障恢复之后，pool能继续请求正常资源必须把此项配置设为false
            breakAfterAcquireFailure: false
            #因性能消耗大,只在需要的时候使用它。如果设为true那么在每个connection提交的时候都将校验其有效
            testConnectionOnCheckout: false
            #如果设为true那么在取得连接的同时将校验连接的有效性。Default: false
            testConnectionOnCheckin: true
            #每60秒检查所有连接池中的空闲连接。Default: 0
            idleConnectionTestPeriod: 60
            #定义在从数据库获取新连接失败后重复尝试的次数。Default: 30
            acquireRetryAttempts: 10
            #两次连接中间隔时间，单位毫秒。Default: 1000
            acquireRetryDelay: 5000
            #获取连接超时时间为10秒，默认则无限等待。设置此值高并发时（连接数占满）可能会引发中断数据库操作风险,单位：毫秒
            checkoutTimeout: 10000
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        format_sql: true
logging:
    level:
        com.netflix: info
        org.springframework.boot: info
    file: /logs/c3p0jpa.log